server:
  port: 8082
  context-path: /product-server
spring:
  datasource:
    url: jdbc:mysql://www.hiyzx.cn:3307/takeaway?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: ENC(wZ3hjZ2E/dJwO2nOFC18xOqDDenossCv)
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
          connection-test-query: select 1 from dual
          connection-timeout: 30000
          idle-timeout: 60000
          max-lifetime: 1800000
          maximum-pool-size: 20
          minimum-idle: 20
  redis:
     database: 1
     host: www.hiyzx.cn
     port: 6379
     password: yzx362311
     timeout: 0
     pool:
        max-active: 20
        min-idle: 5
        max-idle: 10
        max-wait: -1

  dubbo:
    application:
      name: product-server
    registry:
      address: zookeeper://127.0.0.1:2181
    protocol:
      name: dubbo
      port: 20880
    scan: com.zero.product.service

 # data:
  #    elasticsearch:
   #     cluster-name: zero-es
    #    cluster-nodes: 127.0.0.1:9300
     #   repositories:
     #       enabled: true
  http:
    multipart:
      max-file-size: 20mb
      max-request-size: 20mb

logging:
  level:
    com.zero: debug
    org.springframework:
          data: info

jasypt:
  encryptor:
    password: 123456
