server:
  port: 8083
  context-path: /customer
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/takeaway?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=true
    username: root
    password: ENC(97gsusCL76w4MCcfDGUxoA==)
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
          connection-test-query: select 1 from dual
          connection-timeout: 30000
          idle-timeout: 60000
          max-lifetime: 1800000
          maximum-pool-size: 20
          minimum-idle: 20
  redis:
         database: 0
         host: www.hiyzx.cn
         port: 6379
         password: yzx362311
         timeout: 0
         pool:
            max-active: 20
            min-idle: 5
            max-idle: 10
            max-wait: -1
  activemq:
      broker-url: tcp://localhost:61616
      user: admin
      password: admin
      packages:
        trust-all: true
  data:
    elasticsearch:
      cluster-name: zero-es
      cluster-nodes: localhost:9300
      repositories:
          enabled: true

project:
  version: @project.version@
  buildTime: @project.build.time@
  format: @maven.build.timestamp.format@

logging:
  level:
    com.zero: debug

feige:
  secret:
    key: 7d55aa74dbae1c1c0bc68453e3e7742a

http:
  feige:
    scheme: http
    hostname: u.ifeige.cn
    port: 80
  wechat:
    scheme: http
    hostname: sz.api.weixin.qq.com
    port: 80
  remote:
    scheme: https
    hostname: 114.67.147.157
    port: 8080

App:
  grant_type: client_credential
  ID: wx7b599c0943fb598f
  Secret: 40cb7de2d1fcafca438600d6768d462c

jasypt:
  encryptor:
    password: 123456

management:
  security:
    enabled: false