server:
  port: 8010
spring:
  profiles:
    active: dev
  application:
      # 指定注册到eureka server上的服务名称，对于电影微服务，本系列将名称设为microservice-consumer-movie
    name: message-server
  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  boot:
      admin:
        client:
          url: http://localhost:8769

#飞鸽配置
feige:
  secret:
    key: 7d55aa74dbae1c1c0bc68453e3e7742a
http:
  feige:
    scheme: http
    hostname: u.ifeige.cn
    port: 80
# eureka配置
eureka:
  client:
    service-url:
      # 指定eureka server通信地址，注意/eureka/小尾巴不能少
      defaultZone: http://user:123@localhost:8761/eureka/
  instance:
    # 是否注册IP到eureka server，如不指定或设为false，那就会注册主机名到eureka server
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS