server:
  port: 8081
  context-path: /admin
spring:
  redis:
      database: 0
      host: www.hiyzx.cn
      port: 6379
      password: yzx362311
      timeout: 0
      pool:
         max-active: 20
         min-idle: 5
         max-idle: 10
         max-wait: -1
  activemq:
      broker-url: tcp://www.hiyzx.cn:61616
      user: admin
      password: admin
      packages:
        trust-all: true
  application:
      name: admin
  dubbo:
      registry:
         address: zookeeper://127.0.0.1:2181

project:
  version: @project.version@
  buildTime: @project.build.time@
  format: @maven.build.timestamp.format@

logging:
  level:
    com.zero: debug

http:
  juhe:
    scheme: http
    hostname: apis.juhe.cn
    port: 80

jasypt:
  encryptor:
    password: 123456

management:
  security:
    enabled: false