server:
  port: 8000
spring:
  application:
    name: zuul-server
eureka:
  client:
    service-url:
      defaultZone: http://user:123@localhost:8761/eureka/
zuul:
  routes:
    message-server: /message/**

